# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
#
# ,--------.      ,--.   ,--. ,--.
# '--.  .--',---.  \  `.'  /,-'  '-.
#    |  |  | .-. :  .'    \ '-.  .-'
#    |  |  \   --. /  .'.  \  |  |
#    `--'   `----''--'   '--' `--'




## => Site Settings
##############################
text_skin: default # "default" (default), "dark", "forest", "ocean", "chocolate", "orange"
highlight_theme: default # "default" (default), "tomorrow", "tomorrow-night", "tomorrow-night-eighties", "tomorrow-night-blue", "tomorrow-night-bright"
url: https://ec2ez4rd.github.io
baseurl: /
title: EC2EZ4RD's Site
description: >
    EC2EZ4RD's Site | EC2EZ4RD


## => Language and Timezone
##############################
lang: zh
timezone: Asia/Singapore


## => Author and Social
##############################
author:
  name: EC2EZ4RD
  email: rd.wang199@gmail.com
#  twitter: 
  github:  ec2ez4rd
#  googleplus:
#  weibo: 2429275097
#  douban: 


## => GitHub Repository (if the site is hosted by GitHub)
##############################
repository: ec2ez4rd/ec2ez4rd.github.io
repository_tree: master


## => Paths
##############################
paths:
  root: /
  home: /blog
  archive: /blog/archive.html
  rss:  /feed.xml


## => Post
##############################
## excerpt
excerpt_separator: <!--more-->
excerpt_type: html # text (default), html

## license
license: CC-BY-4.0


## => Paginate
##############################
paginate: 7
paginate_path: /blog/page:num


## => Comments
##############################
comments:
  provider: disqus
  disqus:
    shortname: ec2ez4rd-1


## => Pageview
##############################
pageview:
  provider: leancloud
  leancloud:
    app_id: aFKBghGq0bOAqQ2Yu5TrspNc-gzGzoHsz
    app_key: cGh7rcz0TMiEfnIp0S3FCUMP
    app_class: VisitNum


# ## => Analytics
# ##############################
# analytics:
#   provider: google
#   google:
#     tracking_id: UA-71907556-1


## => Build
##############################
markdown: kramdown
highlighter: rouge
permalink: date

exclude:
  - CHANGELOG.md
  - CHECKLIST.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README-*.md
  - README.md
  - gulpfile.js
  - jekyll-text-theme.gemspec
  - package-lock.json
  - package.json
  - /docs
  - /node_modules
  - /screenshots
  - /test
  - /vendor

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: article
      license: true
      aside:
        toc: true
      show_edit_on_github: true
      pageview: true


## => Plugins
##############################
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jemoji


## => Server
##############################
server_url: "0.0.0.0"
port: 4001